### ISSUE TITLE
env vile missing

### ISSUE THREAD

**Issue by JamesCordell** [35grain/label-studio-yolov8-backend#4]
HI I tried to start the docker-compose and I am missing the env file. Can you help please?

**Comment by frankkubler** [comment]
Hi, I encountered the same issue. 
You have to create a .env file in the project root directory which is containing two lines : 
LABEL_STUDIO_BASEURL=http://localhost:8080 or http://yourlabelstudioip:8080 (if localhost connection fail)
LABEL_STUDIO_API_TOKEN=your label studio token

**Comment by 35grain** [comment]
The `.env` file is indeed required. I shall add an example to the project.
